import './experience-card.css';

import {useState} from 'react';

import Badge from '../badge/badge.tsx';
import Modal from '../modal/modal.tsx';

export default function ExperienceCard({index, experience}) {

  /* each experience card has a dialog which work as a modal
  the ID is autogenerated given by the prefix experienceModal and the index
  of the card*/

  const modalId = 'experienceModal' + index;

  const openModal = () => {
    const modalInstance = document.querySelector('#' + modalId);
    modalInstance.showModal();
  };

  const closeModal = () => {
    const modalInstance = document.querySelector('#' + modalId);
    modalInstance.close();
  };

  return (
    <>
      <Modal experience={experience} closeModal={closeModal} modalId={modalId}></Modal>

      <div className='experience-card' onClick={openModal}>
        <h2 className='experience-card-title'>{experience.title}</h2>

        <div className='experience-card-preview'>
          <img src={experience.imagepath}></img>
        </div>

        <div className='experience-card-badges'>
          {experience.badges.map((badge, index) => {
            return (<Badge key={index} content={badge}/>);
          })}
        </div>

        <div className='experience-card-description'>
          <p>
            {experience.description}
          </p>
        </div>
      </div>
    </>
  );
}